version: '3'

services:

  mongodb-latest:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    volumes:
      - ~/Documents/db-data/mongodb:/mongo/db
    ports:
      - "27017:27017"

  mariadb-latest:
    image: mariadb
    restart: always
    environment:
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=dev
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ~/Documents/db-data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
