version: '3'

services:

  mongodb-latest:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    volumes:
      - ~/Documents/db-data/mongodb:/mongo/db
    ports:
      - "27017:27017"

